 name: Demo Workflow
on: workflow_dispatch
jobs: 
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello GH Action!
      - name: Print a in few lines  
        run: | 
          echo First line !
          echo Secon liene ! 
